// generated by scripts/mksyscall.sh syscall/os/linux/syscall_linux_riscv64.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_linux_riscv64.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (vlong)fd, 0, 0, 0, 0, 0);
}

vlong lseek(int fd, vlong offset, int whence)
{
	return (vlong)_syscall6v(SYS_lseek, (vlong)fd, (vlong)offset, (vlong)whence, 0, 0, 0);
}

long openat(int dirfd, void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_openat, (vlong)dirfd, (vlong)path, (vlong)flags, (vlong)mode, 0, 0);
}

int unlinkat(int dirfd, char* path, int flags)
{
	return (int)_syscall6(SYS_unlinkat, (vlong)dirfd, (vlong)path, (vlong)flags, 0, 0, 0);
}

int mkdirat(int dirfd, char* path, int mode)
{
	return (int)_syscall6(SYS_mkdirat, (vlong)dirfd, (vlong)path, (vlong)mode, 0, 0, 0);
}

int faccessat(int dirfd, char* path, int mode, int flags)
{
	return (int)_syscall6(SYS_faccessat, (vlong)dirfd, (vlong)path, (vlong)mode, (vlong)flags, 0, 0);
}

int _sysdup(int fd)
{
	return (int)_syscall6(SYS_dup, (vlong)fd, 0, 0, 0, 0, 0);
}

int dup3(int oldfd, int newfd, int flags)
{
	return (int)_syscall6(SYS_dup3, (vlong)oldfd, (vlong)newfd, (vlong)flags, 0, 0, 0);
}

int chdir(char* path)
{
	return (int)_syscall6(SYS_chdir, (vlong)path, 0, 0, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (vlong)code, 0, 0, 0, 0, 0);
}

uintptr _sysbrk(void* addr)
{
	return (uintptr)_syscall6v(SYS_brk, (vlong)addr, 0, 0, 0, 0, 0);
}

int getpid(void)
{
	return (int)_syscall6(SYS_getpid, 0, 0, 0, 0, 0, 0);
}

long _sysgetcwd(char* buf, ulong size)
{
	return (long)_syscall6(SYS_getcwd, (vlong)buf, (vlong)size, 0, 0, 0, 0);
}

int _sysclockgettime(int clockid, void* ts)
{
	return (int)_syscall6(SYS_clock_gettime, (vlong)clockid, (vlong)ts, 0, 0, 0, 0);
}

int _sysclocknanosleep(int clockid, int flags, void* req, void* rem)
{
	return (int)_syscall6(SYS_clock_nanosleep, (vlong)clockid, (vlong)flags, (vlong)req, (vlong)rem, 0, 0);
}

int _sysfstat(int fd, void* buf)
{
	return (int)_syscall6(SYS_fstat, (vlong)fd, (vlong)buf, 0, 0, 0, 0);
}

int _sysfchmod(int fd, int mode)
{
	return (int)_syscall6(SYS_fchmod, (vlong)fd, (vlong)mode, 0, 0, 0, 0);
}

int _sysftruncate(int fd, vlong length)
{
	return (int)_syscall6(SYS_ftruncate, (vlong)fd, (vlong)length, 0, 0, 0, 0);
}

long _sysgetdents64(int fd, void* buf, uint count)
{
	return (long)_syscall6(SYS_getdents64, (vlong)fd, (vlong)buf, (vlong)count, 0, 0, 0);
}

long _sysrenameat2(int olddirfd, void* oldpath, int newdirfd, void* newpath, uint flags)
{
	return (long)_syscall6(SYS_renameat2, (vlong)olddirfd, (vlong)oldpath, (vlong)newdirfd, (vlong)newpath, (vlong)flags, 0);
}

int _sysrawclone(int flags, void* stack, void* ptid, void* ctid, void* tls)
{
	return (int)_syscall6(SYS_clone, (vlong)flags, (vlong)stack, (vlong)ptid, (vlong)ctid, (vlong)tls, 0);
}

int _sysexecve(void* path, void* argv, void* envp)
{
	return (int)_syscall6(SYS_execve, (vlong)path, (vlong)argv, (vlong)envp, 0, 0, 0);
}

int _syswait4(int pid, void* status, int options, void* rusage)
{
	return (int)_syscall6(SYS_wait4, (vlong)pid, (vlong)status, (vlong)options, (vlong)rusage, 0, 0);
}

int _sysrawpipe2(int* fd, int flags)
{
	return (int)_syscall6(SYS_pipe2, (vlong)fd, (vlong)flags, 0, 0, 0, 0);
}

int _syskill(int pid, int sig)
{
	return (int)_syscall6(SYS_kill, (vlong)pid, (vlong)sig, 0, 0, 0, 0);
}

int _sysrtsigaction(int sig, void* act, void* oact, long sigsetsize)
{
	return (int)_syscall6(SYS_rt_sigaction, (vlong)sig, (vlong)act, (vlong)oact, (vlong)sigsetsize, 0, 0);
}

int _sysioctl(int fd, ulong request, void* arg)
{
	return (int)_syscall6(SYS_ioctl, (vlong)fd, (vlong)request, (vlong)arg, 0, 0, 0);
}

int _syssetitimer(int which, void* new, void* old)
{
	return (int)_syscall6(SYS_setitimer, (vlong)which, (vlong)new, (vlong)old, 0, 0, 0);
}

