// generated by scripts/mksyscall.sh syscall/os/linux/syscall_linux_mips.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_linux_mips.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (long)fd, (long)buf, (long)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (long)fd, (long)buf, (long)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (long)fd, 0, 0, 0, 0, 0);
}

long lseek(int fd, vlong offset, int whence)
{
	return (long)_syscall6(SYS_lseek, (long)fd, (long)offset, (long)whence, 0, 0, 0);
}

long _sysopen(void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_open, (long)path, (long)flags, (long)mode, 0, 0, 0);
}

int _sysunlink(char* path)
{
	return (int)_syscall6(SYS_unlink, (long)path, 0, 0, 0, 0, 0);
}

int _sysrmdir(char* path)
{
	return (int)_syscall6(SYS_rmdir, (long)path, 0, 0, 0, 0, 0);
}

int _sysmkdir(char* path, int mode)
{
	return (int)_syscall6(SYS_mkdir, (long)path, (long)mode, 0, 0, 0, 0);
}

int access(char* path, int mode)
{
	return (int)_syscall6(SYS_access, (long)path, (long)mode, 0, 0, 0, 0);
}

int _sysdup(int fd)
{
	return (int)_syscall6(SYS_dup, (long)fd, 0, 0, 0, 0, 0);
}

int _sysdup2(int oldfd, int newfd)
{
	return (int)_syscall6(SYS_dup2, (long)oldfd, (long)newfd, 0, 0, 0, 0);
}

int chdir(char* path)
{
	return (int)_syscall6(SYS_chdir, (long)path, 0, 0, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (long)code, 0, 0, 0, 0, 0);
}

uintptr _sysbrk(void* addr)
{
	return (uintptr)_syscall6(SYS_brk, (long)addr, 0, 0, 0, 0, 0);
}

int getpid(void)
{
	return (int)_syscall6(SYS_getpid, 0, 0, 0, 0, 0, 0);
}

long _sysgetcwd(char* buf, ulong size)
{
	return (long)_syscall6(SYS_getcwd, (long)buf, (long)size, 0, 0, 0, 0);
}

int _sysclockgettime(int clockid, void* ts)
{
	return (int)_syscall6(SYS_clock_gettime, (long)clockid, (long)ts, 0, 0, 0, 0);
}

int _sysclocknanosleep(int clockid, int flags, void* req, void* rem)
{
	return (int)_syscall6(SYS_clock_nanosleep, (long)clockid, (long)flags, (long)req, (long)rem, 0, 0);
}

int _sysfstat(int fd, void* buf)
{
	return (int)_syscall6(SYS_fstat64, (long)fd, (long)buf, 0, 0, 0, 0);
}

int _sysfchmod(int fd, int mode)
{
	return (int)_syscall6(SYS_fchmod, (long)fd, (long)mode, 0, 0, 0, 0);
}

long openat(int dirfd, void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_openat, (long)dirfd, (long)path, (long)flags, (long)mode, 0, 0);
}

long _sysgetdents64(int fd, void* buf, uint count)
{
	return (long)_syscall6(SYS_getdents64, (long)fd, (long)buf, (long)count, 0, 0, 0);
}

long _sysrenameat2(int olddirfd, void* oldpath, int newdirfd, void* newpath, uint flags)
{
	return (long)_syscall6(SYS_renameat2, (long)olddirfd, (long)oldpath, (long)newdirfd, (long)newpath, (long)flags, 0);
}

int _sysfork(void)
{
	return (int)_syscall6(SYS_fork, 0, 0, 0, 0, 0, 0);
}

int _sysexecve(void* path, void* argv, void* envp)
{
	return (int)_syscall6(SYS_execve, (long)path, (long)argv, (long)envp, 0, 0, 0);
}

int _syswait4(int pid, void* status, int options, void* rusage)
{
	return (int)_syscall6(SYS_wait4, (long)pid, (long)status, (long)options, (long)rusage, 0, 0);
}

int _sysrawpipe2(int* fd, int flags)
{
	return (int)_syscall6(SYS_pipe2, (long)fd, (long)flags, 0, 0, 0, 0);
}

int _syskill(int pid, int sig)
{
	return (int)_syscall6(SYS_kill, (long)pid, (long)sig, 0, 0, 0, 0);
}

int _sysrtsigaction(int sig, void* act, void* oact, long sigsetsize)
{
	return (int)_syscall6(SYS_rt_sigaction, (long)sig, (long)act, (long)oact, (long)sigsetsize, 0, 0);
}

int _sysioctl(int fd, ulong request, void* arg)
{
	return (int)_syscall6(SYS_ioctl, (long)fd, (long)request, (long)arg, 0, 0, 0);
}

int _syssetitimer(int which, void* new, void* old)
{
	return (int)_syscall6(SYS_setitimer, (long)which, (long)new, (long)old, 0, 0, 0);
}

