TOP=../../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libmach_.a

#coupling: if you add a file, you probably need to extend Makefile too
# note that there is no 6db.c because 8db.c is used to disassemble x86(_64)?
OFILES=\
	executable.$O\
	map.$O\
	obj.$O\
	swap.$O\
	sym.$O\
	access.$O\
	machdata.$O\
	setmach.$O\
	5.$O\
	6.$O\
	8.$O\
	5db.$O\
	8db.$O\
	5obj.$O\
	6obj.$O\
	8obj.$O\
        $ostype.$O\

#ifneq ($(GOOS),windows)
#OFILES+=\
#	$(shell uname | tr A-Z a-z).$O\
#else
#OFILES+=\
#	windows.$O\
#endif

HFILES=$TOP/include/ALL/mach.h elf.h macho.h obj.h

<$TOP/mkfiles/mksyslib
