TOP=../../..
<$TOP/mkfiles/$objtype/mkfile

# -lregex for sed and ed
LDLIBS=-lregexp -lbio $BOOTLIBS

# sort: miss tobaserune, join: ?? error j1
TARG=uniq tr ed sed

<$TOP/mkfiles/mkmany

sync:VI:
       syncweb -no_cache -verbose -md5sum_in_auxfile -less_marks -lang C $TOP/principia/docs/principia/Principia.nw $TOP/principia/editors/ed.nw  ed.c

