TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=7l
LDLIBS=-lbio $BOOTLIBS
#LATER: falloc.c mod.c pass.c pobj.c sub.c were actually
# in ld/ in 9cc because forsyth probably thought they 
# were general enough and could be used by other linkers
# but for now I've added just in 7l/ 
OFILES=\
	asm.$O\
	asmout.$O\
	bits.$O\
	cnam.$O\
	dyn.$O\
	falloc.$O\
	list.$O\
	mod.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	pobj.$O\
	span.$O\
	sub.$O\
	enam.$O\
	elf.$O\
	macho.$O\

#HOST=Posix


HFILES=	l.h $TOP/include/obj/7.out.h ../lk/ld.h ../lk/elf.h ../lk/macho.h

CLEANFILES=enam.c

<$TOP/mkfiles/mkone

enam.c: $TOP/include/obj/7.out.h
	sh mkenam

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c

#x:V:	$O.out
#	$O.out -la -o/dev/null x.7

#	$HOST.$O\
#../7c/enam.c: ../7c/7.out.h
#	@ { cd ../7c; mk enam.c }
#enam.$O:	../7c/enam.c
#	$CC $CFLAGS ../7c/enam.c
#cnam.c:	l.h
#	rc ../ld/mkcname


