TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=ia		# also makes ja (for riscv64)
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=	$TOP/include/obj/i.out.h	y.tab.h	a.h

YFILES=a.y
YFLAGS=-D1 -d

<$TOP/mkfiles/mkone

lex.$O:	$TOP/compilers/cck/macbody $TOP/compilers/cck/lexbody $TOP/compilers/cck/compat

# ja is the same binary as ia, just installed under a second name: ia's
# main() (lex.c) already auto-selects thechar='j' (riscv64) when argv[0]'s
# basename starts with 'j', the same convention il/obj.c uses for jl.
install:V:	$BIN/$TARG $BIN/ja
$BIN/ja:	$O.out
	cp $prereq $target

# so 'mk nuke' also removes ja, not just ia (see mkfiles/mkone's nuke:)
NUKEFILES=$BIN/ja
