all:V: float_arm.exe float_arm_.exe 

%.exe: %.s
   5a -c $prereq
   5l -o $target -E _start $stem.5

%_.exe: %.s
   5ag -c $prereq
   5lg -H7 -o $target -E _start $stem.5

clean:V:
	rm -f *.exe *.[5678vi] *.a
