# Build and test goken9cc on Alpine Linux.

FROM alpine:3.21
RUN apk add binutils gcc libc-dev bison make bash ed
# just for lib9/_p9dir.c use of linux/hdreg.h
RUN apk add linux-headers
WORKDIR /src
COPY . .
ENV IN_DOCKER=true
#TODO: switch to all.bash (and later to configure; make; make install)
RUN cd GO/; ./make.bash
ENV PATH="$PATH:/src/bin"

#TODO: can't run hello (or use all.bash above)
# "No such file or directory"
#TODO: RUN make hellogotest
WORKDIR /src/tests/go/hello
RUN make
#TODO: RUN ./hello_go
