TOP=../
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=mk
LDLIBS=-lregexp -lbio -l9 -lm

# Posix.$O below not Plan9.$O!
OFILES=\
    globals.$O\
    utils.$O\
    dumpers.$O\
	archive.$O\
	bufblock.$O\
	env.$O\
	file.$O\
	graph.$O\
	lex.$O\
	main.$O\
	match.$O\
	mk.$O\
	parse.$O\
	rc.$O\
	recipe.$O\
	rule.$O\
	run.$O\
	shprint.$O\
	symtab.$O\
	var.$O\
	varsub.$O\
	word.$O\
     Posix.$O\

HFILES=fns.h mk.h

<$TOP/mkfiles/mkone

# ------------------------------------------------------------------------------
VIEWS=$HFILES ${OFILES:%.o=%.c}
sync:VI:
	for (i in $VIEWS) {
	   syncweb -no_cache -verbose -md5sum_in_auxfile -less_marks -lang C $TOP/principia/builders/Make.nw $TOP/principia/builders/Make_extra.nw  $i
        }
