TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LDLIBS=-lbio $BOOTLIBS

#TODO: could use mkmany but need sed to be in PATH in Dockerfile?
#TODO: dd seems to not work for mk disk in principia so let's skip
TARG=split xd

<$TOP/mkfiles/mkmany
