TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=vc
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	cgen.$O\
	list.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	mul.$O\
        \
	pgen.$O\
	pswt.$O\
	$TOP/linkers/vl/enam.$O\

HFILES= gc.h $TOP/include/obj/v.out.h $TOP/compilers/cck/cc.h

LIB= $TOP/compilers/cck/cc.a$O

<$TOP/mkfiles/mkone

$LIB:
	cd ../cck
	mk all

# see 7c/mkfile for more info
p%.$O: $TOP/compilers/cck/p%.c
	$CC $CFLAGS $TOP/compilers/cck/p$stem.c
