TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=va
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=	$TOP/include/obj/v.out.h y.tab.h a.h

YFILES=a.y\

YFLAGS=-D1 -d

<$TOP/mkfiles/mkone

lex.$O:	$TOP/compilers/cck/macbody $TOP/compilers/cck/lexbody $TOP/compilers/cck/compat
