TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=5a__
LDLIBS=-lbio -l9 -lm
OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=	$TOP/linkers/5l9/5.out.h y.tab.h a.h

YFILES=a.y

YFLAGS=-D1 -d

<$TOP/mkfiles/mkone

lex.$O:	$TOP/src/cmd/cc/macbody $TOP/src/cmd/cc/lexbody
