TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=il		# also makes jl (for riscv64)
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	compress.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	elf.$O\

HFILES=	l.h $TOP/include/obj/i.out.h ../lk/elf.h

CLEANFILES=enam.c

<$TOP/mkfiles/mkone

enam.c: $TOP/include/obj/i.out.h
	sh mkenam

elf.$O:	../lk/elf.c
	$CC $CFLAGS ../lk/elf.c

#	$TARGMODEL.$O\
#enam.$O:	../ic/enam.c
#	$CC $CFLAGS ../ic/enam.c
#$TARGMODEL.$O:	../ld/$TARGMODEL.c
#	$CC $CFLAGS ../ld/$TARGMODEL.c

# jl is the same binary as il, just installed under a second name: il's
# main() (obj.c) already auto-selects thechar='j' (riscv64) when argv[0]'s
# basename starts with 'j' or -j is passed, the same convention ja uses.
install:V:	$BIN/$TARG $BIN/jl
$BIN/jl:	$O.out
	cp $prereq $target

# so 'mk nuke' also removes jl, not just il (see mkfiles/mkone's nuke:)
NUKEFILES=$BIN/jl
