TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=5lk
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	\
	enam.$O\
	elf.$O\

#old: compat.$O or $TARGMODEL.$O

HFILES=	l.h 5.out.h $TOP/include/obj/ar.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: 5.out.h
	sh mkenam
#enam.$O:	../5c/enam.c
#	$CC $CFLAGS ../5c/enam.c

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c
