<$TOP/mkfiles/mkfile.proto

# the goken cross-toolchain itself: used by tests/ (mk objtype=amd64) and,
# once self-hosting is viable, as CC/AS/LD for the top-level build too
O=6
CC=6c
LD=6l
AS=6a
AR=iar

CFLAGS=$CFLAGS_COMMON -I$TOP/include/arch/amd64

# see mkfiles/386/mkfile's identical ARCHEXTRAOFILES comment.
ARCHEXTRAOFILES=arch/amd64/getcallerpc.$O arch/amd64/setjmp.$O
