TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=8lk
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	list.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
        \
	enam.$O\
        elf.$O\

#old: compat.$O or $TARGMODEL.$O

HFILES= l.h 8.out.h  $TOP/include/obj/ar.h


<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: 8.out.h
	sh mkenam

#I added the elf.c/elf.h symlinks instead of reusing
# ../lk/elf.$O to mimic plan9/ code that has those files
# only for 8l
#%.$O:	../lk/%.c
#	$CC $CFLAGS ../lk/$stem.c

#enam.$O:	../8c/enam.c
#	$CC $CFLAGS ../8c/enam.c
