TOP=../..
<$TOP/mkfiles/$objtype/mkfile

# claude: no LDLIBS=$BOOTLIBS here -- see utilities/time/mkfile's
# identical comment (mkfiles/mkone now appends $BOOTLIBS directly).

TARG=grap

#	grapl.$O\

OFILES=\
	y.tab.$O\
	lex.yy.$O\
	main.$O\
	input.$O\
	print.$O\
	frame.$O\
	for.$O\
	coord.$O\
	ticks.$O\
	plot.$O\
	label.$O\
	misc.$O\

HFILES=grap.h y.tab.h

YFILES=grap.y
LFILES=grapl.lx

#alt: YACC=$TOP/generators/yacc/o.out
LEX=$TOP/generators/lex/o.out

<$TOP/mkfiles/mkone

#YFLAGS=-d -S
YFLAGS=-d

LFLAGS=-t

#grap.c:	y.tab.c
#	mv $prereq $target
#
#grapl.c:D: $LFILES
#	$LEX -t $prereq > $target
#
#clean:V:
#	rm -f [$OS].out *.[$OS] y.tab.? lex.yy.c grapl.c grap.c grap
