TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=7c
LDLIBS=-lbio $BOOTLIBS


OFILES=\
	cgen.$O\
	list.$O\
	machcap.$O\
	mul.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
        \
	pgen.$O\
	pswt.$O\
	$TOP/linkers/7l/enam.$O\

HFILES=	gc.h $TOP/include/obj/7.out.h $TOP/compilers/cck/cc.h

LIB=$TOP/compilers/cck/cc.a$O

<$TOP/mkfiles/mkone

$LIB:
	cd ../cck
	mk all

# have to use p% to restrict to pgen/pswt and not enam
# otherwise with just %.$O we get rule ambiguity
p%.$O: $TOP/compilers/cck/p%.c
	$CC $CFLAGS $TOP/compilers/cck/p$stem.c

#$ROOT/$OBJDIR/lib/libcc.a:
#	cd ../cc
#	mk install
#	mk clean
#t:V:	$O.out
#	$O.out -S t
#	$LD -o t.out t.$O
#	t.out
#enam.c: 7.out.h
#	rc mkenam
