TOP=../..
<$TOP/mkfiles/$objtype/mkfile

LIBNAME=libregexp.a

OFILES=\
	regcomp.$O\
	regerror.$O\
	regexec.$O\
	regsub.$O\
	regaux.$O\
	rregexec.$O\
	rregsub.$O\

HFILES=	$TOP/include/ALL/regexp.h regcomp.h

<$TOP/mkfiles/mksyslib
