TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=vl
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	sched.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	\
        enam.$O\
	elf.$O\

#$TARGMODEL.$O\

HFILES= l.h $TOP/include/obj/v.out.h $TOP/include/obj/ar.h

<$TOP/mkfiles/mkone

CLEANFILES=enam.c
enam.c: $TOP/include/obj/v.out.h
	sh mkenam

%.$O:	../lk/%.c
	$CC $CFLAGS ../lk/$stem.c
