TEXT _start+0(SB), $0
	// set up the static base (gp = REGSB = R3) so the global string
	// references generated by ic in main resolve; without it only the
	// first xwrite prints, exactly like start_arm64.s needs setSB in R28.
	MOVW	$setSB(SB), R3
	JAL	R1, main+0(SB)      // R1 = ra (REGLINK); call main
