TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=mtime_float
# claude: no LDLIBS=$BOOTLIBS here -- see utilities/time/mkfile's
# identical comment (mkfiles/mkone now appends $BOOTLIBS directly).

OFILES=mtime_float.$O

<$TOP/mkfiles/mkone
