TOP=../
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=rc

# -lstring is needed just for one function in processes.c (for `{...})
LDLIBS=-lstring -l9 -lm

CFLAGS_EXTRA=-DUnix

# unix.$O this time, not plan9.$O
OFILES=\
	code.$O\
	exec.$O\
	getflags_.$O\
	glob.$O\
	here.$O\
	io.$O\
	lex.$O\
	pcmd.$O\
	pfnc.$O\
	simple.$O\
	trap.$O\
	tree.$O\
	var.$O\
	processes.$O\
     globals.$O\
     utils.$O\
     error.$O\
     words.$O\
     executils.$O\
     status.$O\
     builtins.$O\
     input.$O\
     path.$O\
     env.$O\
     fmt.$O\
     main.$O\
   y.tab.$O \
   unix.$O

HFILES=rc.h\
	io.h\
	exec.h\
	fns.h\
	getflags.h\
	y.tab.h

YFILES=syn.y

<$TOP/mkfiles/mkone

regress: $O.out
	cd test
	mk

unregress:V:
	for(test in test/*.test) rc $test >$test.out

# Test if you can call mk from mk; the PATH should be set correctly
# and propagated to rc (which must do the right finit that set path from PATH).
recmk:
	mk clean

# ------------------------------------------------------------------------------
VIEWS=$HFILES ${OFILES:%.o=%.c}
sync:VI:
	for (i in $VIEWS) {
	   if (~ $i y.tab.[ch]) echo skipping $i
	   if not  syncweb -no_cache -verbose -md5sum_in_auxfile -less_marks -lang C $TOP/principia/shells/Shell.nw $TOP/principia/shells/Shell_extra.nw  $i
        }
