TOP=../..
<$TOP/mkfiles/$objtype/mkfile

# claude: no LDLIBS=$BOOTLIBS here -- see utilities/time/mkfile's
# identical comment (mkfiles/mkone now appends $BOOTLIBS directly).

TARG=pic

#picy.$O picl.$O

OFILES= y.tab.$O\
	lex.yy.$O\
	main.$O\
	print.$O\
	misc.$O\
	symtab.$O\
	blockgen.$O\
	boxgen.$O\
	circgen.$O\
	arcgen.$O\
	linegen.$O\
	movegen.$O\
	textgen.$O\
	input.$O\
	for.$O\
	pltroff.$O\

HFILES=pic.h y.tab.h

YFILES=picy.y
LFILES=picl.lx

<$TOP/mkfiles/mkone

#-S
YFLAGS=-d
LFLAGS=-t

#picy.c:	y.tab.c
#	mv $prereq $target
#
#picl.c:D: picl.lx
#	$LEX -t $prereq > $target
#
#clean:V:
#	rm -f *.[$OS] [$OS].out y.tab.? y.debug $TARG picy.c picl.c
