TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=5c__
LDLIBS=-lbio -l9 -lm

OFILES=\
	cgen.$O\
	list.$O\
	mul.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
        \
	pgen.$O\
	pswt.$O\
	$TOP/linkers/5l9/enam.$O\

HFILES=	gc.h $TOP/linkers/5l9/5.out.h	$TOP/src/cmd/cc/cc.h

LIB=../../src/cmd/cc/cc.a

<$TOP/mkfiles/mkone

# have to use p% to restrict to pgen/pswt and not enam
# otherwise with just %.$O we get rule ambiguity
p%.$O: $TOP/src/cmd/cc/p%.c
	$CC $CFLAGS $TOP/src/cmd/cc/p$stem.c

