// generated by scripts/mksyscall.sh syscall/os/darwin/syscall_darwin_arm64.decl -- DO NOT EDIT

#include <u.h>
#include <libc.h>
#include "syscall_darwin_arm64.h"

long write(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_write, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

long read(int fd, void* buf, long n)
{
	return (long)_syscall6(SYS_read, (vlong)fd, (vlong)buf, (vlong)n, 0, 0, 0);
}

int close(int fd)
{
	return (int)_syscall6(SYS_close, (vlong)fd, 0, 0, 0, 0, 0);
}

vlong lseek(int fd, vlong offset, int whence)
{
	return (vlong)_syscall6v(SYS_lseek, (vlong)fd, (vlong)offset, (vlong)whence, 0, 0, 0);
}

long _sysopen(void* path, int flags, int mode)
{
	return (long)_syscall6(SYS_open, (vlong)path, (vlong)flags, (vlong)mode, 0, 0, 0);
}

int _sysunlink(char* path)
{
	return (int)_syscall6(SYS_unlink, (vlong)path, 0, 0, 0, 0, 0);
}

int _sysrmdir(char* path)
{
	return (int)_syscall6(SYS_rmdir, (vlong)path, 0, 0, 0, 0, 0);
}

int _sysmkdir(char* path, int mode)
{
	return (int)_syscall6(SYS_mkdir, (vlong)path, (vlong)mode, 0, 0, 0, 0);
}

int access(char* path, int mode)
{
	return (int)_syscall6(SYS_access, (vlong)path, (vlong)mode, 0, 0, 0, 0);
}

int _sysdup(int fd)
{
	return (int)_syscall6(SYS_dup, (vlong)fd, 0, 0, 0, 0, 0);
}

int _sysdup2(int oldfd, int newfd)
{
	return (int)_syscall6(SYS_dup2, (vlong)oldfd, (vlong)newfd, 0, 0, 0, 0);
}

int chdir(char* path)
{
	return (int)_syscall6(SYS_chdir, (vlong)path, 0, 0, 0, 0, 0);
}

void exit(int code)
{
	_syscall6(SYS_exit, (vlong)code, 0, 0, 0, 0, 0);
}

uintptr _sysmmap(void* addr, ulong len, int prot, int flags, int fd, vlong offset)
{
	return (uintptr)_syscall6v(SYS_mmap, (vlong)addr, (vlong)len, (vlong)prot, (vlong)flags, (vlong)fd, (vlong)offset);
}

int getpid(void)
{
	return (int)_syscall6(SYS_getpid, 0, 0, 0, 0, 0, 0);
}

int _sysfcntl(int fd, int cmd, void* arg)
{
	return (int)_syscall6(SYS_fcntl, (vlong)fd, (vlong)cmd, (vlong)arg, 0, 0, 0);
}

int _sysgettimeofday(void* tv, void* tz, void* mach)
{
	return (int)_syscall6(SYS_gettimeofday, (vlong)tv, (vlong)tz, (vlong)mach, 0, 0, 0);
}

int _sysselect(int nd, void* in, void* ou, void* ex, void* tv)
{
	return (int)_syscall6(SYS_select, (vlong)nd, (vlong)in, (vlong)ou, (vlong)ex, (vlong)tv, 0);
}

int _sysfstat(int fd, void* buf)
{
	return (int)_syscall6(SYS_fstat64, (vlong)fd, (vlong)buf, 0, 0, 0, 0);
}

int _sysfchmod(int fd, int mode)
{
	return (int)_syscall6(SYS_fchmod, (vlong)fd, (vlong)mode, 0, 0, 0, 0);
}

int _sysftruncate(int fd, vlong length)
{
	return (int)_syscall6(SYS_ftruncate, (vlong)fd, (vlong)length, 0, 0, 0, 0);
}

int _sysexecve(void* path, void* argv, void* envp)
{
	return (int)_syscall6(SYS_execve, (vlong)path, (vlong)argv, (vlong)envp, 0, 0, 0);
}

int _syswait4(int pid, void* status, int options, void* rusage)
{
	return (int)_syscall6(SYS_wait4, (vlong)pid, (vlong)status, (vlong)options, (vlong)rusage, 0, 0);
}

int _syskill(int pid, int sig, int posix)
{
	return (int)_syscall6(SYS_kill, (vlong)pid, (vlong)sig, (vlong)posix, 0, 0, 0);
}

int _sysioctl(int fd, ulong request, void* arg)
{
	return (int)_syscall6(SYS_ioctl, (vlong)fd, (vlong)request, (vlong)arg, 0, 0, 0);
}

int _sysgetdirentries64(int fd, void* buf, ulong bufsize, void* position)
{
	return (int)_syscall6(SYS_getdirentries64, (vlong)fd, (vlong)buf, (vlong)bufsize, (vlong)position, 0, 0);
}

int _syssetitimer(int which, void* new, void* old)
{
	return (int)_syscall6(SYS_setitimer, (vlong)which, (vlong)new, (vlong)old, 0, 0, 0);
}

