TOP=..

DIRS=5i vi

<$TOP/mkfiles/mkdirs

# ------------------------------------------------------------------------------

SRC_VIEWS=\
 5i/arm.h\
 5i/icache.c\
 5i/globals.c\
 5i/utils.c\
 5i/bpt.c\
 5i/mem.c\
 5i/symbols.c\
 5i/run.c\
 5i/5i.c\
 5i/stats.c\
 5i/cmd.c\
 5i/syscall.c\

sync:VI:
	for (i in $SRC_VIEWS) {
	   if (~ $i y.tab.[ch]) echo skipping $i
	   if not {
	     syncweb -no_cache -verbose -md5sum_in_auxfile -less_marks -lang C $TOP/principia/machine/Machine.nw $TOP/principia/machine/Machine_extra.nw  $i
	   }
        }
