TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=8ak
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	y.tab.$O\
	lex.$O\

HFILES=\
	$TOP/linkers/8lk/8.out.h\
	y.tab.h\
	a.h\

YFILES=a.y\

YFLAGS=-D1 -d

<$TOP/mkfiles/mkone

lex.$O:	$TOP/compilers/cck/macbody $TOP/compilers/cck/lexbody
