TOP=../..
<$TOP/mkfiles/$objtype/mkfile

# for ls to remove plan9 specific fcall.h
CFLAGS_EXTRA=-DUnix
# -lstring needed only for du
# -lbio needed only for wc
LDLIBS=-lbio -lstring $BOOTLIBS

# we skip 'cp' as mk install will lead to a "Text file busy" error
# we skip ls, mv, and they are breaking current usage or buggy
# (mv seems to not work)
# we skip chmod seems to not work when used in principia/git9/ mk install
#TODO: mv ls chmod
TARG=cat touch mkdir rm chgrp mtime wc du

<$TOP/mkfiles/mkmany
#<$TOP/mkfiles/mkmanyauto
