TOP=../..
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

TARG=8c
LDLIBS=-lbio -l9 -lm

OFILES=\
	cgen.$O\
	list.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	mul.$O\
        \
	pgen.$O\
	pswt.$O\
        \
	machcap.$O\
	cgen64.$O\
	div.$O\
        \
	$TOP/linkers/8lk/enam.$O\

HFILES=	gc.h $TOP/linkers/8lk/8.out.h $TOP/compilers/cc/cc.h

LIB= $TOP/compilers/cc/cc.a

<$TOP/mkfiles/mkone

p%.$O: $TOP/compilers/cc/p%.c
	$CC $CFLAGS $TOP/compilers/cc/p$stem.c
