#!/bin/sh
# Generates C syscall wrapper functions from a declarative "//sys" spec
# file, in the spirit of GO/pkg/syscall/mksyscall.sh's "//sys name(args)
# (ret) = SYS_NAME" comment convention -- adapted to C, and to a single
# generic 6-arg trampoline (every wrapper just calls _syscall6, padding
# unused argument slots with 0) rather than needing hand-written
# assembly per syscall or per arity.
#
# usage: mksyscall.sh some.decl > zsyscall_xxx.c
# usage: mksyscall.sh some.decl vlong > zsyscall_xxx.c
#
# SYS_NAME may optionally be followed by ":trampoline" (e.g.
# "SYS_lseek:_syscall6v") to call a different trampoline function than
# the default _syscall6 -- used by lseek's decl entries to call
# _syscall6v (same trap sequence as _syscall6, a separate symbol per
# svc_$cputype.s, but declared `vlong`-returning) instead of _syscall6
# (kept plain `long`-returning everywhere, deliberately: the kernel's
# raw 64-bit result gets discarded past 32 bits for every OTHER syscall
# here too, but write/read/close/open's counts and fds are always small
# in practice, so widening the *common* trampoline for the one syscall
# that actually needs the extra 32 bits -- lseek's off_t -- wasn't
# judged worth the risk to the simple, well-exercised default path).
#
# optional 2nd arg (default "long"): the type each argument is cast to
# before being passed into _syscall6. Every arch but one is fine with
# the default -- `long` is always wide enough to carry that arch's own
# pointers without truncation. riscv64 is the exception: like every
# Plan9 C compiler in this tree, its `long` stays 4 bytes even though
# it's a genuine 64-bit arch with 8-byte pointers (see
# include/arch/riscv64/u.h's header comment), so casting e.g. write()'s
# `buf` through `(long)` would silently truncate it. lib_core/libc/mkfile
# passes "vlong" for riscv64 specifically; every other arch's _syscall6
# stays `long`-typed and omits this argument.
#
# deliberately a positional arg, not an environment variable: this
# project's own rc has a no-op Updenv() (see
# docs/claude_notes/notes_libc_selfhost.txt), so a `VAR=val cmd` mkfile
# recipe silently fails to propagate to this script's own subprocess
# (awk) -- a positional arg has no such dependency.
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
	echo "usage: mksyscall.sh file.decl [argtype]" >&2
	exit 1
fi
syscallarg=${2:-long}

base=$(basename "$1" .decl)

echo "// generated by scripts/mksyscall.sh $1 -- DO NOT EDIT"
echo
echo "#include <u.h>"
echo "#include <libc.h>"
echo "#include \"$base.h\""
echo

awk -v syscallarg="$syscallarg" '
/^\/\/sys[ \t]/ {
	line = $0
	sub(/^\/\/sys[ \t]+/, "", line)

	# split "name(params) rettype = SYS_NAME" into its three pieces
	popen = index(line, "(")
	pclose = index(line, ")")
	name = substr(line, 1, popen - 1)
	params = substr(line, popen + 1, pclose - popen - 1)
	rest = substr(line, pclose + 1)
	gsub(/^[ \t]+|[ \t]+$/, "", rest)

	neq = index(rest, "=")
	rettype = substr(rest, 1, neq - 1)
	sysname = substr(rest, neq + 1)
	gsub(/^[ \t]+|[ \t]+$/, "", rettype)
	gsub(/^[ \t]+|[ \t]+$/, "", sysname)

	# optional ":trampoline" suffix on SYS_NAME (see the header comment
	# above) -- defaults to _syscall6
	trampoline = "_syscall6"
	ci = index(sysname, ":")
	if (ci > 0) {
		trampoline = substr(sysname, ci + 1)
		sysname = substr(sysname, 1, ci - 1)
	}

	# claude: "name(void)" means zero arguments, not one argument named
	# "void" -- which is what the generic parse below would otherwise
	# make of it (the parameter name is taken to be the last token, and
	# "void" is the only token), emitting `int getpid(void)` with a
	# `(long)void` argument. Normalized to the empty-parameter case here
	# so the declaration in the .decl can keep saying (void), matching
	# both C and the prototype in include/os/*.h.
	gsub(/^[ \t]+|[ \t]+$/, "", params)
	if (params == "void")
		params = ""

	n = split(params, plist, ",")
	argstr = ""
	callargs = ""
	nargs = 0
	for (i = 1; i <= n; i++) {
		p = plist[i]
		gsub(/^[ \t]+|[ \t]+$/, "", p)
		if (p == "")
			continue
		# the parameter name is the last whitespace-separated
		# token; the type is everything before it
		nsp = split(p, words, " ")
		pname = words[nsp]
		ptype = ""
		for (j = 1; j < nsp; j++)
			ptype = ptype (j > 1 ? " " : "") words[j]
		# a leading "*" on the name (e.g. "void *buf") belongs to
		# the type instead
		while (substr(pname, 1, 1) == "*") {
			ptype = ptype "*"
			pname = substr(pname, 2)
		}
		if (argstr != "")
			argstr = argstr ", "
		argstr = argstr ptype " " pname
		callargs = callargs ", (" syscallarg ")" pname
		nargs++
	}
	for (i = nargs; i < 6; i++)
		callargs = callargs ", 0"

	# emit (void), not (), for a zero-argument syscall -- an empty
	# parameter list is an old-style declaration in C, which these
	# compilers accept but which does not match the (void) prototypes in
	# include/os/*.h
	if (nargs == 0)
		argstr = "void"

	print rettype " " name "(" argstr ")"
	print "{"
	if (rettype == "void")
		print "\t" trampoline "(" sysname callargs ");"
	else
		print "\treturn (" rettype ")" trampoline "(" sysname callargs ");"
	print "}"
	print ""
}
' "$1"
