TOP=../../..
<$TOP/mkfiles/$objtype/mkfile

all:V: helloprintf.exe
clean:V:
	rm -f *.[5678ijv] *.exe *.a
test_one:V:
	mk 'objtype='$cputype all
	./helloprintf.exe | cmp /dev/stdin helloprintf.expected.txt

CPP_FLAGS=-D$objtype

# can use -v for verbose mode to help debug
helloprintf.exe: helloprintf.c
   $CC $CPP_FLAGS -c vlrt.c
   $CC $CPP_FLAGS -c print.c
   $CC $CPP_FLAGS -c helloprintf.c
   $AS $CPP_FLAGS -c linux_$objtype.s
   $AR rc libprint.a linux_$objtype.$O print*.$O vlrt.$O
   $LD -L. -o $target -E _main helloprintf.$O

#TODO: arm_
ARCHS=386 amd64 arm arm64 mips riscv
test:V:
        for (arch in $ARCHS) {
           echo $arch
           mk clean
           mk 'objtype='$arch
           $TOP/scripts/qemu-runner $arch ./helloprintf.exe | cmp /dev/stdin helloprintf.expected.txt
        }


# macOS arm64: Darwin syscall stubs, Mach-O (-H6), mandatory ad-hoc
# signature (see docs/notes_macos.txt). Runs natively on Apple Silicon.
helloprintf_macos_arm64.exe: helloprintf.c
   7c -Darm64 -c vlrt.c
   7c -Darm64 -c print.c
   7c -Darm64 -c helloprintf.c
   7a -Darm64 -c macos_arm64.s
   iar rc libprint.a macos_arm64.7 print*.7 vlrt.7
   7l -H6 -L. -o $target -E _main helloprintf.7
   if(~ `{uname} Darwin) codesign -s - -f $target
   if not true

# runs natively on Apple Silicon (no qemu needed)
test_macos_arm64:V: helloprintf_macos_arm64.exe
	./helloprintf_macos_arm64.exe | cmp /dev/stdin helloprintf.expected.txt

