TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=pcc
# claude: no LDLIBS=$BOOTLIBS here -- see utilities/time/mkfile's
# identical comment (mkfiles/mkone now appends $BOOTLIBS directly).

OFILES=pcc.$O

<$TOP/mkfiles/mkone
