TOP=../..
<$TOP/mkfiles/$objtype/mkfile

# claude: no LDLIBS=$BOOTLIBS here -- see utilities/time/mkfile's
# identical comment (mkfiles/mkone now appends $BOOTLIBS directly).

TARG=eqn
OFILES=main.$O\
	tuning.$O\
	diacrit.$O\
	eqnbox.$O\
	font.$O\
	fromto.$O\
	funny.$O\
	glob.$O\
	integral.$O\
	input.$O\
	lex.$O\
	lookup.$O\
	mark.$O\
	matrix.$O\
	mbwc.$O\
	move.$O\
	over.$O\
	paren.$O\
	pile.$O\
	shift.$O\
	size.$O\
	sqrt.$O\
	text.$O\
	y.tab.$O\

#	eqn.$O\

YFILES=eqn.y

HFILES=e.h y.tab.h

<$TOP/mkfiles/mkone

#YFLAGS=-d -S
YFLAGS=-d

#eqn.c:	y.tab.c prevy.tab.h
#	mv y.tab.c $target
#
#prevy.tab.h:	y.tab.h
#	sh -c 'cmp -s y.tab.h prevy.tab.h || cp y.tab.h prevy.tab.h'
#
#clean:
#	rm -f eqn.c prevy.tab.h
