TOP=..

VIEWS= \
  5l/l.h\
   5l/m.h\
   5l/globals.c\
  5l/asm.c\
   5l/datagen.c\
   5l/codegen.c\
   5l/debugging.c\
  5l/obj.c\
   5l/utils.c\
   5l/dynamic.c\
   5l/io.c\
   5l/lib.c\
   5l/float.c\
   5l/profile.c\
   5l/hist.c\
   5l/main.c\
  5l/pass.c\
   5l/layout.c\
  5l/noop.c\
  5l/optab.c\
  5l/span.c\
  \
  8l/elf.h\
  8l/elf.c\
  \
  5l/fmt.c\
   5l/error.c\
  \
  8l/l.h\
  8l/globals.c\
  8l/utils.c\
  8l/optab.c\
  8l/list.c\
  8l/compat.c\
  8l/pass.c\
  8l/asm.c\
  8l/span.c\
  8l/obj.c\


TODO=\
  ../include/exec/a.out.h\
  ../include/exec/elf.h\
  ../include/obj/ar.h\


sync:VI:
	for (i in $VIEWS) {
	   syncweb -no_cache -verbose -md5sum_in_auxfile -less_marks -lang C $TOP/principia/linkers/Linker.nw $TOP/principia/linkers/Intro.nw $TOP/principia/linkers/Linker_extra.nw $TOP/principia/linkers/Linker_x86.nw   $i
        }
