TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=ic		# also makes jc (for riscv64)
LDLIBS=-lbio $BOOTLIBS

OFILES=\
	cgen.$O\
	list.$O\
	mul.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\
	machcap.$O\
        \
	pgen.$O\
	pswt.$O\
	$TOP/linkers/il/enam.$O\

HFILES=	gc.h $TOP/include/obj/i.out.h $TOP/compilers/cck/cc.h

LIB=$TOP/compilers/cck/cc.a$O

<$TOP/mkfiles/mkone

$LIB:
	cd ../cck
	mk all

# see 7c/mkfile for more info
p%.$O: $TOP/compilers/cck/p%.c
	$CC $CFLAGS $TOP/compilers/cck/p$stem.c

# jc is the same binary as ic, just installed under a second name: ic's
# main() is the shared compilers/cck/lex.c one (used by 7c/vc/ic), which now
# has an argv[0]-basename check for 'j' before it calls ginit() (mirroring
# the ja/jl convention in assemblers/ia/mkfile, linkers/il/mkfile); ic's
# own ginit() (txt.c) picks up thechar='j' from that to select ewidth[TIND]
# and the typeword/typecmplx tables, same idea as compilers/7c/txt.c's
# ginit(), which -- being always arm64/64-bit -- does it unconditionally.
install:V:	$BIN/$TARG $BIN/jc
$BIN/jc:	$O.out
	cp $prereq $target

# so 'mk nuke' also removes jc, not just ic (see mkfiles/mkone's nuke:)
NUKEFILES=$BIN/jc
