TOP=../..
<$TOP/mkfiles/$objtype/mkfile

TARG=5a
LDLIBS=-lbio $BOOTLIBS

OFILES=globals.$O\
	y.tab.$O\
	lex.$O\
	obj.$O\
    main.$O\

HFILES= y.tab.h	a.h $TOP/include/obj/5.out.h

YFILES=a.y

LIB=../as/aa.a$O

<$TOP/mkfiles/mkone

$LIB:
	cd ../as
	mk all

YFLAGS=-D1 -d
