TOP=../../../..
<$TOP/mkfiles/$objtype/mkfile

TARG=5ag
LDLIBS=-lbio -l9 -lm

OFILES=\
	y.tab.$O\
	lex.$O\
	../5l/enam.$O\

HFILES=\
	a.h\
	y.tab.h\
	../5l/5.out.h\

YFILES=a.y

<$TOP/mkfiles/mkone

lex.$O:	../cc/macbody ../cc/lexbody
