TOP=../../../..
<$TOP/mkfiles/$objtype/mkfile

# The directory is prof because the source is portable and general.
# We call the binary 6prof to avoid confusion and because this binary
# is linked only with amd64 and x86 support.

TARG=6prof
# need -lmach too here
LDLIBS=-lmach_ -lbio -l9 -lm

OFILES=\
	main.$O\

<$TOP/mkfiles/mkone
