TOP=../../..
<$TOP/mkfiles/$objtype/mkfile

# $BOOTLIBS (chartorune, a few math functions) is referenced directly
# in each recipe below instead of folded into LDLIBS=$BOOTLIBS here --
# see utilities/time/mkfile's identical comment for why: that
# assignment shape hits a real mk quirk (a stray empty argument
# reaching $LD) once BOOTLIBS is itself unassigned, i.e. for any
# self-hosted (non-boot) objtype.

#TODO: has some segfault hence the _buggy suffix
TARG=awk_buggy
OFILES=re.$O\
	lex.$O\
	main.$O\
	parse.$O\
	proctab.$O\
	tran.$O\
	lib.$O\
	run.$O\
	y.tab.$O\

HFILES=awk.h\
	y.tab.h\
	proto.h\

YFILES=awkgram.y

<$TOP/mkfiles/mkone

proctab.c: y.tab.h maketab.c $O.maketab
	   ./$O.maketab > proctab.c

#TODO: replace by an ed script, like mkenam but mkproctab here
$O.maketab: maketab.$O
	   $LD $LDFLAGS -o $target $prereq $LDLIBS $BOOTLIBS

maketab.$O: maketab.c
	    $CC $CFLAGS $CFLAGS_EXTRA maketab.c

CLEANFILES=$O.maketab proctab.c

#CFLAGS=-FTV -c -D_REGEXP_EXTENSION -D_RESEARCH_SOURCE -D_BSD_EXTENSION -DUTF
#YFLAGS=-S -d -v
#CC=pcc
#LD=pcc
#cpuobjtype=`{sed -n 's/^O=//p' /$cputype/mkfile}
#
#y.tab.h awkgram.c:	$YFILES
#	$YACC -o awkgram.c $YFLAGS $prereq
#proctab.c:	$cpuobjtype.maketab
#	./$cpuobjtype.maketab >proctab.c
#$cpuobjtype.maketab:	y.tab.h maketab.c
#	objtype=$cputype
#	mk maketab.$cputype
#maketab.$cputype:V:	y.tab.h maketab.$O
#	$LD -o $O.maketab maketab.$O
